const workouts = {
  Monday: {
    form: "Chest & Triceps",
    exercises: [
      ["Close Grip Pushups", "Till Failure"],
      ["Barbell Bench Press", "3 sets", "6 reps"],
      ["DB Incline Press", "3 sets", "8 reps"],
      ["Pec Deck", "3 sets", "12 reps"],
      ["Tricep Pressdown", "3 sets", "12 reps"],
      ["DB Skull Crusher", "3 sets", "12 reps"],
    ],
  },
  Tuesday: {
    form: "Back & Biceps",
    exercises: [
      ["Assisted Pullups", "Till Failure"],
      ["Lat Pulldown", "3 sets", "8 reps"],
      ["Seated Cable Row", "3 sets", "10 reps"],
      ["T-bar Row", "3 sets", "12 reps"],
      ["Seated Dumbbell Curl", "3 sets", "12 reps"],
      ["Bayesian Cable Curl", "3 sets", "10 reps"],
      ["Preacher Curl", "3 sets", "10 reps"],
      ["Hammer Curl", "3 sets", "12 reps"],
    ],
  },
  Wednesday: {
    form: "Legs & Shoulders",
    exercises: [
      ["Squats", "Till Failure"],
      ["Smith Machine Squat", "3 sets", "10 reps"],
      ["Leg Press", "3 sets", "12 reps"],
      ["Leg Extension", "3 sets", "15 reps"],
      ["Reverse Pec Deck", "3 sets", "10 reps"],
      ["Machine Shoulder Press", "3 sets", "12 reps"],
      ["Cable Lateral Raises", "3 sets", "10 reps"],
      ["Front Raises", "3 sets", "10 reps"],
    ],
  },
  Thursday: {
    form: "Chest & Triceps",
    exercises: [
      ["Close Grip Pushups", "Till Failure"],
      ["Barbell Bench Press", "3 sets", "6 reps"],
      ["DB Incline Press", "3 sets", "8 reps"],
      ["Pec Deck", "3 sets", "12 reps"],
      ["Tricep Pressdown", "3 sets", "12 reps"],
      ["DB Skull Crusher", "3 sets", "12 reps"],
    ],
  },
  Friday: {
    form: "Back & Biceps",
    exercises: [
      ["Assisted Pullups", "Till Failure"],
      ["Lat Pulldown", "3 sets", "8 reps"],
      ["Seated Cable Row", "3 sets", "10 reps"],
      ["T-bar Row", "3 sets", "12 reps"],
      ["Seated Dumbbell Curl", "3 sets", "12 reps"],
      ["Bayesian Cable Curl", "3 sets", "10 reps"],
      ["Preacher Curl", "3 sets", "10 reps"],
      ["Hammer Curl", "3 sets", "12 reps"],
    ],
  },
  Saturday: {
    form: "Legs & Shoulders",
    exercises: [
      ["Squats", "Till Failure"],
      ["Smith Machine Squat", "3 sets", "10 reps"],
      ["Leg Press", "3 sets", "12 reps"],
      ["Leg Extension", "3 sets", "15 reps"],
      ["Reverse Pec Deck", "3 sets", "10 reps"],
      ["Machine Shoulder Press", "3 sets", "12 reps"],
      ["Cable Lateral Raises", "3 sets", "10 reps"],
      ["Front Raises", "3 sets", "10 reps"],
    ],
  },
  Sunday: { form: "Rest", exercises: [] },
};
